name: Docker Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v2
      with:
        image: tonistiigi/binfmt:latest
        platforms: amd64,arm64

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get next version
      id: get_next_version
      uses: thenativeweb/get-next-version@main

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: casmith/pgsqldump:${{ steps.get_next_version.outputs.version }},casmith/pgsqldump:latest
        platforms: linux/amd64,linux/arm64

    - name: Build and push restore
      id: docker_build_restore
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: casmith/pgsqlrestore:${{ steps.get_next_version.outputs.version }},casmith/pgsqlrestore:latest
        platforms: linux/amd64,linux/arm64
        file: Dockerfile.restore
      
